// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfEBqyjvWIrIuKrELGB9ezo3lA2g42zeI',
    appId: '1:413210933362:web:1a738ef799138bba086aeb',
    messagingSenderId: '413210933362',
    projectId: 'mad-practice-74780',
    authDomain: 'mad-practice-74780.firebaseapp.com',
    storageBucket: 'mad-practice-74780.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuzfM-iHXE2Rb82GkeYmp15fXHWHKruBQ',
    appId: '1:413210933362:android:fd07967dfca654da086aeb',
    messagingSenderId: '413210933362',
    projectId: 'mad-practice-74780',
    storageBucket: 'mad-practice-74780.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeqET9YhwkZZnKN4tDwRLrdypSDwStg5M',
    appId: '1:413210933362:ios:f74b6d7bb5b4da24086aeb',
    messagingSenderId: '413210933362',
    projectId: 'mad-practice-74780',
    storageBucket: 'mad-practice-74780.firebasestorage.app',
    iosClientId: '413210933362-4mh9flqkgv1dvmch6bdf3qsjq46upapo.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeqET9YhwkZZnKN4tDwRLrdypSDwStg5M',
    appId: '1:413210933362:ios:f74b6d7bb5b4da24086aeb',
    messagingSenderId: '413210933362',
    projectId: 'mad-practice-74780',
    storageBucket: 'mad-practice-74780.firebasestorage.app',
    iosClientId: '413210933362-4mh9flqkgv1dvmch6bdf3qsjq46upapo.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfEBqyjvWIrIuKrELGB9ezo3lA2g42zeI',
    appId: '1:413210933362:web:f9c38f708bf13fc8086aeb',
    messagingSenderId: '413210933362',
    projectId: 'mad-practice-74780',
    authDomain: 'mad-practice-74780.firebaseapp.com',
    storageBucket: 'mad-practice-74780.firebasestorage.app',
  );
}
